algoritmo "semnome"
// Função :
// Autor :
// Data : 10/11/2015
// Seção de Declarações 
var
n1, n2, n3, media: real
cont: inteiro
inicio


      para cont de 1 ate 50 passo 1 faca
      escreval (cont,"º ALUNO")
      escreva ("NOTA 1: ")
      leia (n1)
      escreva ("NOTA 2: ")
      leia (n2)
      escreva ("NOTA 3: ")
      leia (n3)

      media<-(n1+n2+n3)/3
      escreval ("Média final: ",media)

      fimpara
fimalgoritmo
