algoritmo "semnome"
// Função :
// Autor :
// Data : 03/11/2015
// Seção de Declarações 
var
bmaior, bmenor, altura, area: real
inicio
      escreval ("ÁREA DO TRAPÉZIO")
      escreva ("Digite o tamanho da base maior: ")
      leia (bmaior)
      escreva ("Digite o tamanho da base menor: ")
      leia (bmenor)
      escreva ("Digite o tamanho da altura: ")
      leia (altura)
      
      area <- ((bmaior+bmenor)*altura)/2
      escreva ("ÁREA: ",area)

fimalgoritmo
