algoritmo "semnome"
// Função :
// Autor :
// Data : 03/11/2015
// Seção de Declarações 
var
raio, altura, volume: real
inicio
      escreval ("VOLUME DE UM CILINDRO")
      
      escreva ("Digite o tamanho do raio: ")
      leia (raio)
      escreva ("Digite o tamanho da altura: ")
      leia (altura)
      
      volume <- (raio*3.14*2)*altura
      
      escreva ("VOLUME: ", volume)
fimalgoritmo
