algoritmo "semnome"
// Função :
// Autor :
// Data : 06/11/2015
// Seção de Declarações 
var
nome: caractere
distancia, tempo: real
inicio
      escreva ("NOME: ")
      leia (nome)
      escreva ("DISTÂNCIA (km): ")
      leia (distancia)
      escreva("TEMPO (h): ")
      leia (tempo)
      escreva ("A velocidade média do(a) piloto(a) ",nome," foi ",distancia/tempo," km/h.")
fimalgoritmo
