algoritmo "semnome"
// Função :
// Autor :
// Data : 06/11/2015
// Seção de Declarações 
var
numero: inteiro
inicio
      escreva ("Digite um numero positivo: ")
      leia (numero)
      
      se numero>0 entao
         se (numero%2)=0 entao
            escreva ("Esse número é par!")
         senao
            escreva ("Esse número é impar!")
         fimse
      fimse
      se numero<0 entao
           escreva ("Esse numero é negativo!")
      fimse
fimalgoritmo
